
main: main.cpp
	#g++ --std=c++11 main.cpp -I/home/daniel/git/promolden++/armadillo-9.100.5/include -llapack -L/home/daniel/git/promolden++/armadillo-9.100.5 -o main
	#g++ --std=c++11 main.cpp -I/home/daniel/git/promolden++/armadillo-9.100.5/include -L/usr/lib64/libblas.so.3 -L/usr/lib64/liblapack.so.3 -L/home/daniel/git/promolden++/armadillo-9.100.5 -o main
	#g++ --std=c++11 main.cpp -I/home/daniel/git/promolden++/armadillo-9.100.5/include -L/usr/lib64/ -L/home/daniel/git/promolden++/armadillo-9.100.5 -o main
	#g++ --std=c++11 main.cpp -I/home/daniel/git/promolden++/armadillo-9.100.5/include -llapack -L/home/daniel/git/promolden++/armadillo-9.100.5 -o main
	g++ --std=c++11 main.cpp -I./include -L/usr/lib64/liblapack.so.3 -L/usr/lib64/libblas.so.3 -L/usr/lib64/libgfortran.so -o main
	#g++ --std=c++11 main.cpp -llapack -o main
